// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace qm_test
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Quamotion.CodedUI.Controls;
    using Quamotion.CodedUI.Controls.Android;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class UIMap
    {
        
        #region Properties
        public UILoginActivityactivity UILoginActivityactivity
        {
            get
            {
                if ((this.mUILoginActivityactivity == null))
                {
                    this.mUILoginActivityactivity = new UILoginActivityactivity();
                }
                return this.mUILoginActivityactivity;
            }
        }
        #endregion
        
        #region Fields
        private UILoginActivityactivity mUILoginActivityactivity;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UILoginActivityactivity : MobileTestControl
    {
        
        public UILoginActivityactivity()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "activity";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "mobi.quamotion.android.activity";
            this.SearchProperties["DeviceClassName"] = "mobi.quamotion.android.activity";
            this.SearchProperties[UITestControl.PropertyNames.TechnologyName] = "Quamotion";
            this.SearchProperties["Index"] = "0";
            this.SearchProperties["id"] = null;
            #endregion
        }
        
        #region Properties
        public UIGroupgroup UIGroupgroup
        {
            get
            {
                if ((this.mUIGroupgroup == null))
                {
                    this.mUIGroupgroup = new UIGroupgroup(this);
                }
                return this.mUIGroupgroup;
            }
        }
        #endregion
        
        #region Fields
        private UIGroupgroup mUIGroupgroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIGroupgroup : MobileTestControl
    {
        
        public UIGroupgroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "group";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "mobi.quamotion.group";
            this.SearchProperties["DeviceClassName"] = "mobi.quamotion.group";
            this.SearchProperties[UITestControl.PropertyNames.TechnologyName] = "Quamotion";
            this.SearchProperties["FilteredWidgetsXPath"] = "com.android.internal.policy.impl.PhoneWindow..DecorView[1]/android.widget.LinearL" +
                "ayout[1]";
            #endregion
        }
        
        #region Properties
        public UIDrawer_layoutgroup UIDrawer_layoutgroup
        {
            get
            {
                if ((this.mUIDrawer_layoutgroup == null))
                {
                    this.mUIDrawer_layoutgroup = new UIDrawer_layoutgroup(this);
                }
                return this.mUIDrawer_layoutgroup;
            }
        }
        #endregion
        
        #region Fields
        private UIDrawer_layoutgroup mUIDrawer_layoutgroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIDrawer_layoutgroup : MobileTestControl
    {
        
        public UIDrawer_layoutgroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "group";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "mobi.quamotion.group";
            this.SearchProperties["DeviceClassName"] = "mobi.quamotion.group";
            this.SearchProperties[UITestControl.PropertyNames.TechnologyName] = "Quamotion";
            this.SearchProperties["FilteredWidgetsXPath"] = "android.widget.FrameLayout[@Id=\'content\'][1]/android.support.v4.widget.DrawerLayo" +
                "ut[@Id=\'drawer_layout\'][1]";
            #endregion
        }
        
        #region Properties
        public UIGroupgroup2 UIGroupgroup
        {
            get
            {
                if ((this.mUIGroupgroup == null))
                {
                    this.mUIGroupgroup = new UIGroupgroup2(this);
                }
                return this.mUIGroupgroup;
            }
        }
        #endregion
        
        #region Fields
        private UIGroupgroup2 mUIGroupgroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIGroupgroup2 : MobileTestControl
    {
        
        public UIGroupgroup2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "group";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "mobi.quamotion.group";
            this.SearchProperties["DeviceClassName"] = "mobi.quamotion.group";
            this.SearchProperties[UITestControl.PropertyNames.TechnologyName] = "Quamotion";
            this.SearchProperties["FilteredWidgetsXPath"] = "android.widget.FrameLayout[@Id=\'main_frame\'][1]/android.widget.FrameLayout[1]";
            #endregion
        }
        
        #region Properties
        public UIGroupgroup1 UIGroupgroup1
        {
            get
            {
                if ((this.mUIGroupgroup1 == null))
                {
                    this.mUIGroupgroup1 = new UIGroupgroup1(this);
                }
                return this.mUIGroupgroup1;
            }
        }
        
        public UILinearLayoutLinearLayout2 UILinearLayoutLinearLayout
        {
            get
            {
                if ((this.mUILinearLayoutLinearLayout == null))
                {
                    this.mUILinearLayoutLinearLayout = new UILinearLayoutLinearLayout2(this);
                }
                return this.mUILinearLayoutLinearLayout;
            }
        }
        #endregion
        
        #region Fields
        private UIGroupgroup1 mUIGroupgroup1;
        
        private UILinearLayoutLinearLayout2 mUILinearLayoutLinearLayout;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIGroupgroup1 : MobileTestControl
    {
        
        public UIGroupgroup1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "group";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "mobi.quamotion.group";
            this.SearchProperties["DeviceClassName"] = "mobi.quamotion.group";
            this.SearchProperties[UITestControl.PropertyNames.TechnologyName] = "Quamotion";
            this.SearchProperties["FilteredWidgetsXPath"] = "android.widget.LinearLayout[1]/android.widget.LinearLayout[1]";
            #endregion
        }
        
        #region Properties
        public UIGroupgroup3 UIGroupgroup
        {
            get
            {
                if ((this.mUIGroupgroup == null))
                {
                    this.mUIGroupgroup = new UIGroupgroup3(this);
                }
                return this.mUIGroupgroup;
            }
        }
        #endregion
        
        #region Fields
        private UIGroupgroup3 mUIGroupgroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIGroupgroup3 : MobileTestControl
    {
        
        public UIGroupgroup3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "group";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "mobi.quamotion.group";
            this.SearchProperties["DeviceClassName"] = "mobi.quamotion.group";
            this.SearchProperties[UITestControl.PropertyNames.TechnologyName] = "Quamotion";
            this.SearchProperties["FilteredWidgetsXPath"] = "android.widget.LinearLayout[1]/android.widget.LinearLayout[1]";
            #endregion
        }
        
        #region Properties
        public UILinearLayoutLinearLayout UILinearLayoutLinearLayout
        {
            get
            {
                if ((this.mUILinearLayoutLinearLayout == null))
                {
                    this.mUILinearLayoutLinearLayout = new UILinearLayoutLinearLayout(this);
                }
                return this.mUILinearLayoutLinearLayout;
            }
        }
        #endregion
        
        #region Fields
        private UILinearLayoutLinearLayout mUILinearLayoutLinearLayout;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UILinearLayoutLinearLayout : LinearLayout
    {
        
        public UILinearLayoutLinearLayout(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "LinearLayout";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "android.widget.LinearLayout";
            this.SearchProperties["DeviceClassName"] = "android.widget.LinearLayout";
            this.SearchProperties[UITestControl.PropertyNames.TechnologyName] = "Quamotion";
            this.SearchProperties["Index"] = "1";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "android.widget.LinearLayout";
            this.SearchProperties["Id"] = null;
            #endregion
        }
        
        #region Properties
        public UILinearLayoutLinearLayout1 UILinearLayoutLinearLayout1
        {
            get
            {
                if ((this.mUILinearLayoutLinearLayout1 == null))
                {
                    this.mUILinearLayoutLinearLayout1 = new UILinearLayoutLinearLayout1(this);
                }
                return this.mUILinearLayoutLinearLayout1;
            }
        }
        #endregion
        
        #region Fields
        private UILinearLayoutLinearLayout1 mUILinearLayoutLinearLayout1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UILinearLayoutLinearLayout1 : LinearLayout
    {
        
        public UILinearLayoutLinearLayout1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "LinearLayout";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "android.widget.LinearLayout";
            this.SearchProperties["DeviceClassName"] = "android.widget.LinearLayout";
            this.SearchProperties[UITestControl.PropertyNames.TechnologyName] = "Quamotion";
            this.SearchProperties["Index"] = "0";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "android.widget.LinearLayout";
            this.SearchProperties["Id"] = null;
            #endregion
        }
        
        #region Properties
        public Button ContinueAsGuest
        {
            get
            {
                if ((this.mContinueAsGuest == null))
                {
                    this.mContinueAsGuest = new Button(this);
                    #region Search Criteria
                    this.mContinueAsGuest.SearchProperties[UITestControl.PropertyNames.ControlType] = "Button";
                    this.mContinueAsGuest.SearchProperties[UITestControl.PropertyNames.ClassName] = "android.widget.Button";
                    this.mContinueAsGuest.SearchProperties["DeviceClassName"] = "android.widget.Button";
                    this.mContinueAsGuest.SearchProperties[UITestControl.PropertyNames.TechnologyName] = "Quamotion";
                    this.mContinueAsGuest.SearchProperties["Index"] = "0";
                    this.mContinueAsGuest.SearchProperties[UITestControl.PropertyNames.ClassName] = "android.widget.Button";
                    this.mContinueAsGuest.SearchProperties["Id"] = "login_guest_button";
                    this.mContinueAsGuest.SearchProperties["Text"] = "Continue as guest";
                    #endregion
                }
                return this.mContinueAsGuest;
            }
        }
        #endregion
        
        #region Fields
        private Button mContinueAsGuest;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UILinearLayoutLinearLayout2 : LinearLayout
    {
        
        public UILinearLayoutLinearLayout2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "LinearLayout";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "android.widget.LinearLayout";
            this.SearchProperties["DeviceClassName"] = "android.widget.LinearLayout";
            this.SearchProperties[UITestControl.PropertyNames.TechnologyName] = "Quamotion";
            this.SearchProperties["Index"] = "0";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "android.widget.LinearLayout";
            this.SearchProperties["Id"] = null;
            #endregion
        }
        
        #region Properties
        public UIGroupgroup4 UIGroupgroup
        {
            get
            {
                if ((this.mUIGroupgroup == null))
                {
                    this.mUIGroupgroup = new UIGroupgroup4(this);
                }
                return this.mUIGroupgroup;
            }
        }
        #endregion
        
        #region Fields
        private UIGroupgroup4 mUIGroupgroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIGroupgroup4 : MobileTestControl
    {
        
        public UIGroupgroup4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "group";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "mobi.quamotion.group";
            this.SearchProperties["DeviceClassName"] = "mobi.quamotion.group";
            this.SearchProperties[UITestControl.PropertyNames.TechnologyName] = "Quamotion";
            this.SearchProperties["FilteredWidgetsXPath"] = "android.widget.ScrollView[1]/android.widget.LinearLayout[1]";
            #endregion
        }
        
        #region Properties
        public UIGroupgroup11 UIGroupgroup1
        {
            get
            {
                if ((this.mUIGroupgroup1 == null))
                {
                    this.mUIGroupgroup1 = new UIGroupgroup11(this);
                }
                return this.mUIGroupgroup1;
            }
        }
        #endregion
        
        #region Fields
        private UIGroupgroup11 mUIGroupgroup1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIGroupgroup11 : MobileTestControl
    {
        
        public UIGroupgroup11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "group";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "mobi.quamotion.group";
            this.SearchProperties["DeviceClassName"] = "mobi.quamotion.group";
            this.SearchProperties[UITestControl.PropertyNames.TechnologyName] = "Quamotion";
            this.SearchProperties["FilteredWidgetsXPath"] = "android.widget.LinearLayout[1]/android.widget.LinearLayout[1]";
            #endregion
        }
        
        #region Properties
        public UILinearLayoutLinearLayout3 UILinearLayoutLinearLayout
        {
            get
            {
                if ((this.mUILinearLayoutLinearLayout == null))
                {
                    this.mUILinearLayoutLinearLayout = new UILinearLayoutLinearLayout3(this);
                }
                return this.mUILinearLayoutLinearLayout;
            }
        }
        #endregion
        
        #region Fields
        private UILinearLayoutLinearLayout3 mUILinearLayoutLinearLayout;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UILinearLayoutLinearLayout3 : LinearLayout
    {
        
        public UILinearLayoutLinearLayout3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "LinearLayout";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "android.widget.LinearLayout";
            this.SearchProperties["DeviceClassName"] = "android.widget.LinearLayout";
            this.SearchProperties[UITestControl.PropertyNames.TechnologyName] = "Quamotion";
            this.SearchProperties["Index"] = "0";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "android.widget.LinearLayout";
            this.SearchProperties["Id"] = null;
            #endregion
        }
        
        #region Properties
        public UILinearLayoutLinearLayout11 UILinearLayoutLinearLayout1
        {
            get
            {
                if ((this.mUILinearLayoutLinearLayout1 == null))
                {
                    this.mUILinearLayoutLinearLayout1 = new UILinearLayoutLinearLayout11(this);
                }
                return this.mUILinearLayoutLinearLayout1;
            }
        }
        #endregion
        
        #region Fields
        private UILinearLayoutLinearLayout11 mUILinearLayoutLinearLayout1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UILinearLayoutLinearLayout11 : LinearLayout
    {
        
        public UILinearLayoutLinearLayout11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "LinearLayout";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "android.widget.LinearLayout";
            this.SearchProperties["DeviceClassName"] = "android.widget.LinearLayout";
            this.SearchProperties[UITestControl.PropertyNames.TechnologyName] = "Quamotion";
            this.SearchProperties["Index"] = "0";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "android.widget.LinearLayout";
            this.SearchProperties["Id"] = null;
            #endregion
        }
        
        #region Properties
        public UIGroupgroup5 UIGroupgroup
        {
            get
            {
                if ((this.mUIGroupgroup == null))
                {
                    this.mUIGroupgroup = new UIGroupgroup5(this);
                }
                return this.mUIGroupgroup;
            }
        }
        #endregion
        
        #region Fields
        private UIGroupgroup5 mUIGroupgroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIGroupgroup5 : MobileTestControl
    {
        
        public UIGroupgroup5(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "group";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "mobi.quamotion.group";
            this.SearchProperties["DeviceClassName"] = "mobi.quamotion.group";
            this.SearchProperties[UITestControl.PropertyNames.TechnologyName] = "Quamotion";
            this.SearchProperties["FilteredWidgetsXPath"] = "com.lufthansa.android.lufthansa.ui.custom.FloorplanButton[@Id=\'ac_floorplanbutton" +
                "_flightstatus\'][1]/android.widget.LinearLayout[1]";
            #endregion
        }
        
        #region Properties
        public TextView CheckFlightStatus
        {
            get
            {
                if ((this.mCheckFlightStatus == null))
                {
                    this.mCheckFlightStatus = new TextView(this);
                    #region Search Criteria
                    this.mCheckFlightStatus.SearchProperties[UITestControl.PropertyNames.ControlType] = "TextView";
                    this.mCheckFlightStatus.SearchProperties[UITestControl.PropertyNames.ClassName] = "android.widget.TextView";
                    this.mCheckFlightStatus.SearchProperties["DeviceClassName"] = "android.widget.TextView";
                    this.mCheckFlightStatus.SearchProperties[UITestControl.PropertyNames.TechnologyName] = "Quamotion";
                    this.mCheckFlightStatus.SearchProperties["Index"] = "0";
                    this.mCheckFlightStatus.SearchProperties[UITestControl.PropertyNames.ClassName] = "android.widget.TextView";
                    this.mCheckFlightStatus.SearchProperties["Id"] = "wg_floorplanbutton_textview";
                    this.mCheckFlightStatus.SearchProperties["Text"] = "Flight status";
                    #endregion
                }
                return this.mCheckFlightStatus;
            }
        }
        #endregion
        
        #region Fields
        private TextView mCheckFlightStatus;
        #endregion
    }
}
